module.exports = {
    trailingComma: 'es5',
    useTabs: false,
    printWidth: 80,
    semi: false,
    singleQuote: true,
    tabWidth: 2,
    trailingComma: 'all',
    bracketSpacing: true,
    semi: false,
    jsxSingleQuote: true,
    jsxBracketSameLine: false,
    arrowParens: 'avoid',
    requirePragma: false,
    insertPragma: true,
}
